mail_tracker_web/mail_tracker_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls'))
]

mail_tracker_web/web/urls.py
from django.urls import path, include
from .views import (
    RegisterView,
    LoginView,
    LogoutView,
    IndexView,
    MessageDetailView,
    DeleteMessageView,
    SendEmailView
)


auth_paths = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('messages/<int:message_id>/', MessageDetailView.as_view(), name='message_detail'),
    path('delete/<int:message_id>/', DeleteMessageView.as_view(), name='delete_message'),
    path('send-email/', SendEmailView.as_view(), name='send_email'),
    path('auth/', include((auth_paths, 'web'), namespace='auth')),
]

mail_tracker_web/web/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, BaseUserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class BaseUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

mail_tracker_web/web/forms.py
from django import forms


class RegisterForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())


class SendEmailForm(forms.Form):
    recipient = forms.EmailField()
    subject = forms.CharField()
    content = forms.CharField(widget=forms.Textarea())

mail_tracker_web/web/views.py
from django.views.generic import FormView, TemplateView, View
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.db import IntegrityError
from django.conf import settings

from .permissions import AnonymousRequiredPermission
from .forms import RegisterForm, LoginForm, SendEmailForm
from .models import BaseUser
from .utils import parse_list_message, send_email, EstablishConnection
from .mixins import ContextMixin


class RegisterView(AnonymousRequiredPermission, FormView):
    form_class = RegisterForm
    success_url = reverse_lazy('auth:login')
    template_name = 'register.html'

    def form_valid(self, form):
        try:
            BaseUser.objects.create_user(email=form.cleaned_data.get('email'),
                                         password=form.cleaned_data.get('password'),
                                         is_active=True)
        except IntegrityError as exc:
            form.add_error('email', 'This user already exists')
            return super().form_invalid(form)

        return super().form_valid(form)


class LoginView(AnonymousRequiredPermission, FormView):
    form_class = LoginForm
    success_url = reverse_lazy('index')
    template_name = 'login.html'

    def form_valid(self, form):
        user_qs = BaseUser.objects.filter(email=form.cleaned_data.get('email'))

        if user_qs.exists():
            user = user_qs.first()

            if user.check_password(form.cleaned_data.get('password')):
                login(self.request, user)

                return super().form_valid(form)

        form.add_error(field=None, error='Could not authenticate with the provided credentials')

        return super().form_invalid(form)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)

        return redirect(reverse('index'))


class IndexView(LoginRequiredMixin, ContextMixin, TemplateView):
    login_url = reverse_lazy('auth:login')

    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        with EstablishConnection() as connection:
            connection.send(settings.POP3_LIST_COMMAND.format(request.user.email.split('@')[0]).encode('utf-8'))
            data = connection.receive()
            parsed_data = parse_list_message(data.decode('utf-8'))

            self.context = {
                'response': parsed_data[0],
                'content': parsed_data[1]
            }

        return super().get(request, *args, **kwargs)


class MessageDetailView(LoginRequiredMixin, ContextMixin, TemplateView):
    login_url = reverse_lazy('auth:login')
    template_name = 'message_detail.html'

    def get(self, request, *args, **kwargs):
        with EstablishConnection() as connection:
            connection.send(settings.POP3_RETRIEVE_COMMAND.format(kwargs.get('message_id')).encode('utf-8'))
            data = connection.receive()

            self.context = {
                'received_data': data.decode('utf-8'),
                'message_id': kwargs.get('message_id')
            }

        return super().get(request, *args, **kwargs)


class DeleteMessageView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        with EstablishConnection() as connection:
            connection.send(settings.POP3_DELETE_COMMAND.format(
                request.user.email.split('@')[0],
                kwargs.get('message_id')).encode('utf-8'))

        return redirect('index')


class SendEmailView(LoginRequiredMixin, FormView):
    form_class = SendEmailForm
    success_url = reverse_lazy('index')
    template_name = 'send_email.html'

    def form_valid(self, form):
        sender = self.request.user.email.split('@')[0] + '@localhost.com'
        send_email(sender,
                   form.cleaned_data.get('subject'),
                   [form.cleaned_data.get('recipient')],
                   form.cleaned_data.get('content'))

        return super().form_valid(form)

mail_tracker_web/templates/base.html
<!doctype html>
<html>
  <head>
    <title>
      {% block "title" %}
      {% endblock %}
    </title>
    <meta charset="utf-8" />
  </head>
  <body>
    {% block "body" %}
    {% endblock %}
  </body>
</html>

mail_tracker_web/templates/form_errors.html
<ul>
  {% for field, error in form.errors.items %}
    <li>{{ field }}: {{ error }}</li>
  {% endfor %}
</ul>

mail_tracker_web/templates/index.html
{% extends "base.html" %}
{% load extra_tags %}

{% block "title" %}
  Messages
{% endblock %}

{% block "body" %}
  <h1>
    <a href="{% url "send_email" %}"><button>Send email</button></a>
    <a href="{% url "auth:logout" %}"><button>Logout</button></a>
    <br/>
  {{ response }}
  <br/>
  {% for line in content %}
    {{ line|get_item:"subject" }} --- {{ line|get_item:"id" }}
    <a href="{% url "message_detail" line|get_item:"id" %}"><button>View</button></a> <br/>
  {% endfor %}
</h1>
{% endblock %}

mail_tracker_web/templates/login.html
{% extends "base.html" %}

{% block "title" %}
  Log In
{% endblock %}

{% block "body" %}
  <form method="POST" action={% url "auth:login" %}>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Log In"/>
  </form>
  <br/>
  <a href="{% url "auth:register" %}"><button>Sign Up</button></a>
{% endblock %}

mail_tracker_web/templates/message_detail.html
{% extends "base.html" %}

{% block "title" %}
  Message
{% endblock %}

{% block "body" %}
  <pre>
    {{ received_data }}
  </pre>
  <a href={% url "delete_message" message_id %}><button>Delete message</button></a>
{% endblock %}

mail_tracker_web/templates/register.html
{% extends "base.html" %}

{% block "title" %}
  Register
{% endblock %}

{% block "body" %}
  <form method="POST" action={% url "auth:register" %}>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Sign Up"/>
  </form>
{% endblock%}

mail_tracker_web/templates/send_email.html
{% extends "base.html" %}

{% block "title" %}
  Send Email
{% endblock %}

{% block "body" %}
  <form method="POST" action={% url "send_email" %}>
    {% csrf_token %}
    {% for field in form %}
      {{ field.label }}<br/>
      {{ field }}<br/>
    {% endfor %}
    <input type="submit" value="Send"/>
  </form>
{% endblock %}